// Generated by contracts/generate.py from report-upload.schema.json.
import Foundation
extension GrpcReportPayload {
    internal func generatedWireDictionary() -> [String: Any] {
        var result: [String: Any] = [:]
        result["sig_ver"] = sigVer
        if let value = reAttestationAssertion?.base64EncodedString() { result["re_attestation_assertion"] = value }
        result["ts"] = ts
        if let value = trustLevel?.rawValue { result["trust_level"] = value }
        if let value = bindingDigest { result["binding_digest"] = value }
        if let value = attestationKeyId { result["attestation_key_id"] = value }
        if let value = outputPathIntegrity { result["output_path_integrity"] = value }
        result["nonce"] = nonce
        result["session_token"] = sessionToken
        result["device_id"] = deviceId
        result["scene"] = scene
        result["payload_json"] = payloadJson.base64EncodedString()
        if let value = attestationAssertion?.base64EncodedString() { result["attestation_assertion"] = value }
        result["app_id"] = appId
        result["sdk_version"] = sdkVersion
        if let value = bindingMode { result["binding_mode"] = value }
        result["kind"] = "sdk_report"
        result["payload_sha256"] = payloadSha256.base64EncodedString()
        result["report_id"] = reportId
        result["contract_version"] = 1
        result["key_id"] = keyId
        result["signature"] = signature
        if let value = fieldMappingVersion { result["field_mapping_version"] = value }
        return result
    }
}
