"""Generate both wire boundaries from the HTTP schema. --check is the CI gate."""
import json, pathlib, sys
ROOT=pathlib.Path(__file__).resolve().parents[1]
schema=json.loads((ROOT/'contracts/report-upload.schema.json').read_text())
py='''# Generated by contracts/generate.py; do not edit.\nSCHEMA = '''+repr(schema)+'''

def validate_shape(value):
    if not isinstance(value,dict): raise ValueError('expected object')
    if set(value)-set(SCHEMA['properties']): raise ValueError('unknown upload field')
    if set(SCHEMA['required'])-set(value): raise ValueError('missing required field')
    for name, item in value.items():
        rule=SCHEMA['properties'][name]
        if 'const' in rule and (type(item) is not type(rule['const']) or item!=rule['const']): raise ValueError('invalid '+name)
        kind=rule.get('type')
        if kind=='string' and (not isinstance(item,str) or len(item)<rule.get('minLength',0)): raise ValueError('invalid '+name)
        if kind=='integer' and (type(item) is not int or item<rule.get('minimum',item) or item>=rule.get('exclusiveMaximum',item+1)): raise ValueError('invalid '+name)
        if kind=='object' and (not isinstance(item,dict) or any(not isinstance(k,str) or not isinstance(v,str) for k,v in item.items())): raise ValueError('invalid '+name)
    return value
'''
swift=['// Generated by contracts/generate.py from report-upload.schema.json.','import Foundation','extension GrpcReportPayload {','    internal func generatedWireDictionary() -> [String: Any] {','        var result: [String: Any] = [:]']
for name,rule in schema['properties'].items():
    expr=rule['x-swift-expression']
    if name in schema['required']: swift.append(f'        result["{name}"] = {expr}')
    else: swift.append(f'        if let value = {expr} {{ result["{name}"] = value }}')
swift+=['        return result','    }','}']
outputs={ROOT/'contracts/generated_contract.py':py,ROOT/'RiskDetectorApp/Sources/CloudPhoneRiskKit/Risk/GeneratedReportWire.swift':'\n'.join(swift)+'\n'}
for path,content in outputs.items():
    if '--check' in sys.argv:
        if not path.exists() or path.read_text()!=content: raise SystemExit('stale generated file: '+str(path))
    else: path.write_text(content)
