#ifndef CPRISK_VM_INTERPRETER_H
#define CPRISK_VM_INTERPRETER_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Build-time producer + runtime consumer ABI (Pass13 VMProtector). */
#define CPRISK_VMP_MAGIC_DISPATCH 0x44565043u /* "CPVD" little-endian */
#define CPRISK_VMP_MAGIC_BYTECODE 0x4D565043u /* "CPVM" little-endian */
#define CPRISK_VMP_VERSION 1u
/** M2: optional VPC affine + extended header (global vpc_a/vpc_b after base header). */
#define CPRISK_VMP_VERSION_M2 2u
#define CPRISK_VMP_CLASS_TABLE_BYTES 256u

/** Bitmask in \c cprisk_vmp_bytecode_header_t::reserved (producer may set). */
#define CPRISK_VMP_BC_FLAG_NONE 0u
/** When set, \c reserved also carries a 2-bit handler variant seed (see M2). */
#define CPRISK_VMP_BC_FLAG_HANDLER_VARIANT_SEED 0x00000001u
/** Each bytecode entry is followed by 16 bytes: vpc_a, vpc_b (LE uint64 each). */
#define CPRISK_VMP_BC_FLAG_PER_ENTRY_VPC 0x00000002u
/** M3: dispatch loop uses opaque predicate gates (non-linear CFG, semantics unchanged). */
#define CPRISK_VMP_BC_FLAG_M3_OPAQUE_CHAIN 0x00000004u
/** M3: inject unreachable / bait handler paths (seed from \c reserved bits 16–23). */
#define CPRISK_VMP_BC_FLAG_M3_DEAD_HANDLERS 0x00000008u
/** M3: run interpreter entry self-check (rolling hash vs \c CPRISK_VM_M3_SELF_EXPECT). */
#define CPRISK_VMP_BC_FLAG_M3_SELFCHK 0x00000010u

enum {
    CPRISK_VM_STATUS_OK = 0,
    CPRISK_VM_STATUS_INVALID_DISPATCH = 1,
    CPRISK_VM_STATUS_INVALID_BYTECODE = 2,
    CPRISK_VM_STATUS_TRACED_SHORTCIRCUIT = 3,
    CPRISK_VM_STATUS_STEP_LIMIT = 4,
};

enum {
    CPRISK_VM_POISON_NONE = 0u,
    CPRISK_VM_POISON_UNKNOWN_OPCODE = 1u << 0,
    CPRISK_VM_POISON_TRACED = 1u << 1,
    CPRISK_VM_POISON_FRIDA = 1u << 2,
    CPRISK_VM_POISON_DISPATCH = 1u << 3,
    CPRISK_VM_POISON_BYTECODE = 1u << 4,
    /** M3: interpreter entry self-check mismatch (tamper / unexpected layout). */
    CPRISK_VM_POISON_SELF_INTEGRITY = 1u << 5,
};

/**
 * M3 optional: expected FNV-1a (32-bit) of the first \c CPRISK_VM_M3_SELF_BYTES bytes of
 * \c cprisk_vm_execute in the linked TEXT segment (no address mixing; stable under ASLR).
 * When 0, the self-check is skipped even if \c CPRISK_VMP_BC_FLAG_M3_SELFCHK is set.
 * Enable a strict check by defining this at compile time to the fingerprint for your
 * toolchain (e.g. arm64 -O2 reference: \c 0x2f32ecc6u for the object file produced
 * from this source snapshot; re-derive after material interpreter changes).
 */
#if !defined(CPRISK_VM_M3_SELF_EXPECT)
#define CPRISK_VM_M3_SELF_EXPECT 0u
#endif
#if !defined(CPRISK_VM_M3_SELF_BYTES)
#define CPRISK_VM_M3_SELF_BYTES 96u
#endif

/* Logical opcode IDs generated by VMProtector/VMIR.swift. */
enum {
    CPRISK_VM_OP_NOP = 0u,
    CPRISK_VM_OP_RET = 1u,
    CPRISK_VM_OP_RAW_REGION = 2u,
    CPRISK_VM_OP_HALT = 3u,
    /** M2: byte-lane add into acc (multiple semantic-equivalent handler paths). */
    CPRISK_VM_OP_ADD = 4u,
    CPRISK_VM_OP_POISON = 0xFFu
};

typedef struct cprisk_vmp_dispatch_header {
    uint32_t magic;
    uint32_t version;
    uint32_t class_table_size;
    uint32_t flags;
} cprisk_vmp_dispatch_header_t;

typedef struct cprisk_vmp_bytecode_header {
    uint32_t magic;
    uint32_t version;
    uint32_t entry_count;
    /** Legacy: 0. M2: \c CPRISK_VMP_BC_FLAG_* ; low bits may select handler variant seed. */
    uint32_t reserved;
} cprisk_vmp_bytecode_header_t;

typedef struct cprisk_vmp_bytecode_entry {
    uint64_t function_id;
    uint64_t original_entry_vma;
    uint32_t tier;
    uint32_t bytecode_offset;
    uint32_t bytecode_length;
    uint32_t reserved;
} cprisk_vmp_bytecode_entry_t;

typedef struct cprisk_vm_run_result {
    uint32_t status;
    uint32_t poison_flags;
    uint32_t whitebox_domain_rc;
    uint8_t acc[32];
    uint64_t steps;
    uint32_t last_opcode;
    uint32_t last_dispatch_class;
} cprisk_vm_run_result_t;

/// Execute VM bytecode for the given function id.
/// Returns a 64-bit value folded from VM accumulator (reserved for ABI compatibility).
uint64_t cprisk_vm_entry(uint64_t func_id);

/// Debug/testing entry: execute VM and emit detailed run result.
/// Returns 0 on success, -1 on invalid input.
int cprisk_vm_execute(uint64_t func_id, cprisk_vm_run_result_t *out);

/// Returns \c CPRISK_ARMOR_CAP_VMP_RUNTIME when both VMP sections parse as minimally valid.
uint32_t cprisk_vm_query_armor_capability_bits(void);

#ifdef __cplusplus
}
#endif

#endif /* CPRISK_VM_INTERPRETER_H */
