name: RiskDetectorApp
options:
  bundleIdPrefix: com.cloudphonerisk
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  CloudPhoneRiskKit:
    path: .

targets:
  RiskDetectorApp:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "**/*.xcassets"
    resources:
      - path: App/Resources/Assets.xcassets
      - path: App/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cloudphonerisk.riskdetector
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: CloudPhoneRiskKit
        product: CloudPhoneRiskKit
      - package: CloudPhoneRiskKit
        product: CloudPhoneRiskAppCore

schemes:
  RiskDetectorApp:
    build:
      targets:
        RiskDetectorApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
